version: "3"

services:
  ms-wkspc-demo-golang:
    container_name: ms-wkspc-demo-golang
    build:
      context: ms-demo-golang
    volumes:
      - ./ms-demo-golang:/go/src/app
      ## Remove the following line if you are checking-in your dependencies 
      - /go/src/app/vendor
    expose:
      - 77701
    ports:
      - 7701:7701
    environment:
      - APP_ENV=development
      - PORT=7701
      - DBNAME=microservices_demo
      - DBUSER=microservices_demo
      - DBPASS=microservices_demo_pw
      - DBADDR=msa_demo_db:3306
      - DEBUG=1
    command: /go/bin/CompileDaemon -build="go-wrapper install" -command="go-wrapper run" -exclude-dir=.git
    depends_on:
      - msa_demo_db
    links:
      - msa_demo_db

  # Kong API Gateway
  kong:
    container_name: kong
    image: kong
    links:
      - kong_db
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong_db
      - KONG_PG_USER=kong
      - KONG_PG_DATABASE=kong
      - KONG_PG_PASSWORD=kong_pw
    expose: 
      - 8000
      - 8001
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    depends_on:
      - kong_db
    links:
      - ms-wkspc-demo-golang
  
  msa_demo_db:
    container_name: msa_demo_db
    image: mysql:5.7
    # port mapping not required for microservices but useful for debugging from 
    # host machine, during development
    ports: 
      - 33306:3306
    volumes:
      - msa_demo_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: verysecretsomething
      MYSQL_DATABASE: microservices_demo
      MYSQL_USER: microservices_demo
      MYSQL_PASSWORD: microservices_demo_pw
  
  kong_db:
    container_name: kong_db
    image: postgres:9.4
    # port mapping not required for microservices but useful for debugging from 
    # host machine, during development
    ports:
      - 35432:5432
    volumes:
      - kong_db_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong_pw

volumes:
  msa_demo_db_data:
  kong_db_data:

